import base64
import hashlib
import string

class Base64Strategy:
    """Strategy for generating short codes using base64 encoding"""

    @staticmethod
    def encode_url(long_url, length=6):
        """
        Generate a short code for a URL using base64 encoding

        Args:
            long_url (str): The original URL to shorten
            length (int): Desired length of the short code (default: 6)

        Returns:
            str: A base64-encoded short code
        """
        # Create a hash of the URL for consistency
        url_hash = hashlib.md5(long_url.encode('utf-8')).digest()

        # Encode to base64
        encoded = base64.b64encode(url_hash).decode('utf-8')

        # Make it URL-safe by replacing problematic characters
        url_safe = encoded.replace('+', '-').replace('/', '_').rstrip('=')

        # Return the desired length
        return url_safe[:length]

    # URL-safe base64 alphabet (after +/ are swapped for -_ and padding stripped)
    CHARSET = string.ascii_letters + string.digits + '-_'

    @staticmethod
    def is_valid_short_code(short_code):
        """
        Validate if a short code was generated by this strategy

        Args:
            short_code (str): The short code to validate

        Returns:
            bool: True if valid, False otherwise
        """
        return bool(short_code) and all(c in Base64Strategy.CHARSET for c in short_code)

    @staticmethod
    def get_strategy_name():
        """Get the name of this strategy"""
        return "base64"

