import hashlib
import time
import string

class HashingStrategy:
    """Strategy for generating short codes using hash-based encoding"""

    # Character set for short codes (alphanumeric + some symbols)
    CHARSET = string.ascii_letters + string.digits + '-_'
    BASE = len(CHARSET)

    @staticmethod
    def encode_url(long_url, length=6):
        """
        Generate a short code for a URL using hash-based encoding

        Args:
            long_url (str): The original URL to shorten
            length (int): Desired length of the short code (default: 6)

        Returns:
            str: A hash-based short code
        """
        # Create a hash of the URL combined with timestamp for uniqueness
        timestamp = str(int(time.time() * 1000000))  # microsecond precision
        combined = (long_url + timestamp).encode('utf-8')
        hash_obj = hashlib.sha256(combined)
        hash_int = int(hash_obj.hexdigest(), 16)

        # Convert to base-N representation using our charset
        short_code = ""
        while hash_int > 0 and len(short_code) < length:
            short_code = HashingStrategy.CHARSET[hash_int % HashingStrategy.BASE] + short_code
            hash_int //= HashingStrategy.BASE

        # Pad with random chars if too short
        while len(short_code) < length:
            short_code = HashingStrategy.CHARSET[hash_int % HashingStrategy.BASE] + short_code
            hash_int = (hash_int * 31 + ord(long_url[len(short_code) % len(long_url)])) % (10**9)

        return short_code[:length]

    @staticmethod
    def is_valid_short_code(short_code):
        """
        Validate if a short code was generated by this strategy

        Args:
            short_code (str): The short code to validate

        Returns:
            bool: True if valid, False otherwise
        """
        return all(c in HashingStrategy.CHARSET for c in short_code)

    @staticmethod
    def get_strategy_name():
        """Get the name of this strategy"""
        return "hashing"